spring:
  application:
    name: phonebook
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  datasource:
    url: ${DB_HOST:localhost}/${DB_NAME:phonebook}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pass}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true